/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArcadeRouteImport } from './routes/arcade'
import { Route as PlayRouteImport } from './routes/play'
import { Route as ArcadeIndexRouteImport } from './routes/arcade/index'
import { Route as ArcadeGameIdRouteImport } from './routes/arcade/$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeRoute = ArcadeRouteImport.update({
  id: '/arcade',
  path: '/arcade',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeIndexRoute = ArcadeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArcadeRoute,
} as any)
const ArcadeGameIdRoute = ArcadeGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => ArcadeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRouteWithChildren
  '/play': typeof PlayRoute
  '/arcade/$gameId': typeof ArcadeGameIdRoute
  '/arcade/': typeof ArcadeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/play': typeof PlayRoute
  '/arcade/$gameId': typeof ArcadeGameIdRoute
  '/arcade': typeof ArcadeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRouteWithChildren
  '/play': typeof PlayRoute
  '/arcade/$gameId': typeof ArcadeGameIdRoute
  '/arcade/': typeof ArcadeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/arcade' | '/play' | '/arcade/$gameId' | '/arcade/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/play' | '/arcade/$gameId' | '/arcade'
  id: '__root__' | '/' | '/arcade' | '/play' | '/arcade/$gameId' | '/arcade/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArcadeRoute: typeof ArcadeRouteWithChildren
  PlayRoute: typeof PlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade': {
      id: '/arcade'
      path: '/arcade'
      fullPath: '/arcade'
      preLoaderRoute: typeof ArcadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade/': {
      id: '/arcade/'
      path: '/'
      fullPath: '/arcade/'
      preLoaderRoute: typeof ArcadeIndexRouteImport
      parentRoute: typeof ArcadeRoute
    }
    '/arcade/$gameId': {
      id: '/arcade/$gameId'
      path: '/$gameId'
      fullPath: '/arcade/$gameId'
      preLoaderRoute: typeof ArcadeGameIdRouteImport
      parentRoute: typeof ArcadeRoute
    }
  }
}

interface ArcadeRouteChildren {
  ArcadeGameIdRoute: typeof ArcadeGameIdRoute
  ArcadeIndexRoute: typeof ArcadeIndexRoute
}

const ArcadeRouteChildren: ArcadeRouteChildren = {
  ArcadeGameIdRoute: ArcadeGameIdRoute,
  ArcadeIndexRoute: ArcadeIndexRoute,
}

const ArcadeRouteWithChildren =
  ArcadeRoute._addFileChildren(ArcadeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArcadeRoute: ArcadeRouteWithChildren,
  PlayRoute: PlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
